/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppConcluidoRouteImport } from './routes/app.concluido'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppTreinoRouteImport } from './routes/app.treino'
import { Route as AppExerciciosIndexRouteImport } from './routes/app.exercicios.index'
import { Route as AppExerciciosSlugRouteImport } from './routes/app.exercicios.$slug'
import { Route as AppSessaoWorkoutIdRouteImport } from './routes/app.sessao.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConcluidoRoute = AppConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinoRoute = AppTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosIndexRoute = AppExerciciosIndexRouteImport.update({
  id: '/exercicios/',
  path: '/exercicios/',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosSlugRoute = AppExerciciosSlugRouteImport.update({
  id: '/exercicios/$slug',
  path: '/exercicios/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppSessaoWorkoutIdRoute = AppSessaoWorkoutIdRouteImport.update({
  id: '/sessao/$workoutId',
  path: '/sessao/$workoutId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/concluido': typeof AppConcluidoRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/exercicios/$slug': typeof AppExerciciosSlugRoute
  '/app/sessao/$workoutId': typeof AppSessaoWorkoutIdRoute
  '/app/exercicios/': typeof AppExerciciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/concluido': typeof AppConcluidoRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/exercicios/$slug': typeof AppExerciciosSlugRoute
  '/app/sessao/$workoutId': typeof AppSessaoWorkoutIdRoute
  '/app/exercicios': typeof AppExerciciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/concluido': typeof AppConcluidoRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/treino': typeof AppTreinoRoute
  '/app/exercicios/$slug': typeof AppExerciciosSlugRoute
  '/app/sessao/$workoutId': typeof AppSessaoWorkoutIdRoute
  '/app/exercicios/': typeof AppExerciciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/concluido'
    | '/app/inicio'
    | '/app/treino'
    | '/app/exercicios/$slug'
    | '/app/sessao/$workoutId'
    | '/app/exercicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/concluido'
    | '/app/inicio'
    | '/app/treino'
    | '/app/exercicios/$slug'
    | '/app/sessao/$workoutId'
    | '/app/exercicios'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/concluido'
    | '/app/inicio'
    | '/app/treino'
    | '/app/exercicios/$slug'
    | '/app/sessao/$workoutId'
    | '/app/exercicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/concluido': {
      id: '/app/concluido'
      path: '/concluido'
      fullPath: '/app/concluido'
      preLoaderRoute: typeof AppConcluidoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treino': {
      id: '/app/treino'
      path: '/treino'
      fullPath: '/app/treino'
      preLoaderRoute: typeof AppTreinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercicios/': {
      id: '/app/exercicios/'
      path: '/exercicios'
      fullPath: '/app/exercicios/'
      preLoaderRoute: typeof AppExerciciosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercicios/$slug': {
      id: '/app/exercicios/$slug'
      path: '/exercicios/$slug'
      fullPath: '/app/exercicios/$slug'
      preLoaderRoute: typeof AppExerciciosSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessao/$workoutId': {
      id: '/app/sessao/$workoutId'
      path: '/sessao/$workoutId'
      fullPath: '/app/sessao/$workoutId'
      preLoaderRoute: typeof AppSessaoWorkoutIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConcluidoRoute: typeof AppConcluidoRoute
  AppInicioRoute: typeof AppInicioRoute
  AppTreinoRoute: typeof AppTreinoRoute
  AppExerciciosSlugRoute: typeof AppExerciciosSlugRoute
  AppSessaoWorkoutIdRoute: typeof AppSessaoWorkoutIdRoute
  AppExerciciosIndexRoute: typeof AppExerciciosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConcluidoRoute: AppConcluidoRoute,
  AppInicioRoute: AppInicioRoute,
  AppTreinoRoute: AppTreinoRoute,
  AppExerciciosSlugRoute: AppExerciciosSlugRoute,
  AppSessaoWorkoutIdRoute: AppSessaoWorkoutIdRoute,
  AppExerciciosIndexRoute: AppExerciciosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
